In [2]:
import pandas as pd

In [3]:
df = pd.read_parquet('input/bases_osa.parquet')
df

,DATA,CNPJ,CATEGORIA,FAMILIA,SELLOUT_TON,SELLOUT_REAIS
0,2023-01-01,10194833000194,BISCUITS,BELVITA,0.267600,0.00
1,2023-01-01,10194833000194,BISCUITS,CLUB SOCIAL,3.599200,0.00
2,2023-01-01,10194833000194,BISCUITS,OREO,1.557800,0.00
3,2023-01-01,10194833000194,BISCUITS,OTHER BISCUITS,0.098600,0.00
4,2023-01-01,10194833000194,BISCUITS,TRAKINAS,3.798867,0.00
...,...,...,...,...,...,...
22553568,2024-12-01,97422620007910,PB,CLIGHT,0.002984,515.53
22553569,2024-12-01,97422620007910,PB,FRESH,0.001425,131.55
22553570,2024-12-01,97422620007910,PB,TANG,0.011448,861.73
22553571,2024-12-01,97550909000155,PB,CLIGHT,0.030000,0.00
22553572,2024-12-01,97550909000155,PB,TANG,0.090000,0.00

In [4]:
df = df[df['DATA'] >= '2025-01-01']
df.to_parquet('osa_p01_p08_25.parquet', index=False)

In [5]:
df

,DATA,CNPJ,CATEGORIA,FAMILIA,SELLOUT_TON,SELLOUT_REAIS
476058,2025-01-01,10194833000194,BISCUITS,76222105283000,0.025350,0.00
476059,2025-01-01,10194833000194,BISCUITS,76222105283300,0.016725,0.00
476060,2025-01-01,10194833000194,BISCUITS,76222105286900,0.058725,0.00
476061,2025-01-01,10194833000194,BISCUITS,76222105287200,0.024750,0.00
476062,2025-01-01,10194833000194,BISCUITS,76222105322500,0.152562,0.00
...,...,...,...,...,...,...
16671352,2025-08-01,97422620007163,PB,76222106963372,0.000480,48.70
16671353,2025-08-01,97422620007163,PB,76222106963773,0.001680,142.10
16671354,2025-08-01,97422620007163,PB,76222106964473,0.003168,188.44
16671355,2025-08-01,97422620007163,PB,76222106965973,0.000976,100.08
16671356,2025-08-01,97422620007163,PB,76222106966373,0.000600,69.95